# GitHub Copilot Code Review configuration
auto_review:
  # Ask Copilot to perform code reviews in Japanese
  locale: ja
  instructions_file: 
    .github/rules.md
    .github/copilot-instructions.md
  ignore_patterns:
    - "docs/**"
