services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    # commandディレクティブを削除。コンテナ起動時のコマンドはDockerfileのENTRYPOINTとCMDで制御します。
    ports:
      - "9000:9000"
      - "${VITE_PORT:-5173}:5173"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "88:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    platform: linux/amd64
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:

networks:
  default:
    driver: bridge
