name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, pdo_mysql
      - name: Install composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G

  pest:
    runs-on: ubuntu-latest
    needs: phpstan
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, pdo_mysql
      - name: Install composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Run Pest Tests
        run: vendor/bin/pest --verbose

  npm-test:
    runs-on: ubuntu-latest
    needs: pest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm dependencies
        run: npm ci
      - name: Run Vitest tests
        run: npm run test -- --run
